config/routes.rb
Rails.application.routes.draw do
  # Scope manages languages
  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    # Only for logged-in users
    devise_for :users
    authenticate :user do
      resources :videos, except: [:index, :show]
      resources :illustrations, except: [:index, :show]
      resources :items, except: [:index, :show]
    end

    # Public stuff
    resources :videos, only: [:index, :show]
    resources :illustrations, only: [:index, :show]
    resources :items, only: [:index, :show]
    get :vocabulary, to: 'items#vocabulary'
    get :proverbs, to: 'items#proverbs'
    get :idioms, to: 'items#idioms'
    get :ateji, to: 'items#ateji'
    get '/contact', to: 'welcomes#contact'

    # Main page
    root to: 'welcomes#index'

    # All other routes are an error, they go home
    get '*path', to: 'welcomes#index'
  end

  # Redirect to language
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: { path: /(?!(#{I18n.available_locales.join('|')})\/).*/ }, format: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_attached_file :image, styles: {
    small: '100x100>',
    medium: '500x500>',
    large: '1000x1000>'
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/illustration.rb
class Illustration < ApplicationRecord
  has_attached_file :image, styles: {
    small: '100x100>',
    medium: '500x500>',
    large: '1000x1000>'
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/item.rb
class Item < ApplicationRecord
  include SearchCop

  search_scope :search do
    attributes :category
  end

  def to_param
    self.slug
  end
  
  before_save :create_slug
  
  private
 
  def create_slug
    self.slug = self.word.downcase.strip.gsub(' ', '-')
  end
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  include SearchCop

  search_scope :search do
    attributes :category
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  helper_method :switch_language_path, :current_path_new_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def current_path_new_locale(new_locale)
    locale = I18n.default_locale
    I18n.available_locales.each do |lan|
      if new_locale == lan
        locale = "/#{lan}"
      end
    end
    request.path.sub(/\/(#{I18n.available_locales.join('|')})/, locale)
  end

protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :time_zone, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :time_zone, :email, :password, :current_password])
  end

end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  before_action :set_illustration, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  def index
    @illustrations = Illustration.order("created_at DESC").page(params[:page]).per(10)
  end

  def show
  end

  def new
    @illustration = Illustration.new
  end

  def edit
  end

  def create
    @illustration = Illustration.new(illustration_params)

    if @illustration.save
      redirect_to @illustration, notice: 'Illustration was successfully created.'
    else
      render :new
    end
  end

  def update
    if @illustration.update(illustration_params)
      redirect_to @illustration, notice: 'Illustration was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @illustration.destroy
    redirect_to illustrations_url, notice: 'Illustration was successfully destroyed.'
  end

  private
    def set_illustration
      @illustration = Illustration.find(params[:id])
    end

    def illustration_params
      params.require(:illustration).permit(:title, :image, :blurb)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order(:reading).page(params[:page])
  end

  def vocabulary
    @items = Item.all.search("category: 'Vocab'").order(:reading).page(params[:page])
  end

  def proverbs
    @items = Item.all.search("category: 'kotowaza'").order(:reading).page(params[:page])
  end

  def idioms
    @items = Item.all.search("category: 'yjjg'").order(:reading).page(params[:page])
  end

  def ateji
    @items = Item.all.search("category: 'ateji'").order(:reading).page(params[:page])
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    def set_item
      @item = Item.find_by(slug: params[:id])
    end
    def item_params
      params.require(:item).permit(:key, :word, :reading, :english, :notes, :synonyms, :opposites, :found_in, :japanese, :origin, :test, :level, :category)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.order(created_at: :desc)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def video_params
    params.require(:video).permit(:title, :tag)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    @items = Item.order('RANDOM()').limit(1)
    @videos = Video.last(1)
    @illustrations = Illustration.last(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/illustrations/_form.html.haml
= simple_form_for(@illustration, multipart: true) do |f|
  - if @illustration.errors.any?
    #error_explanation
      %h2= "#{pluralize(@illustration.errors.count, "error")} prohibited this illustration from being saved:"
      %ul
        - @illustration.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title
  = f.input :image, as: :file
  = f.input :blurb, as: :text
  = f.button :submit

app/views/illustrations/edit.html.haml
%h1 Editing illustration

= render 'form'

= link_to 'Show', @illustration
\|
= link_to 'Back', illustrations_path

app/views/illustrations/index.html.haml
%h1
  %span.mdi.mdi-cards
  Illustrations
%br
- if user_signed_in?
  = link_to 'New Illustration', new_illustration_path, class: 'btn btn-success'
  %br
  %br
- @illustrations.each_slice(2) do |row|
  .row
    - row.each do |illustration|
      .col-sm-6
        = link_to illustration do
          .card
            %h5.card-header
              = illustration.title
            .card-block
              = image_tag illustration.image.url(:medium), class: 'img-fluid img-rounded'
              = simple_format illustration.blurb
              - if user_signed_in?
                %br
                = link_to 'Edit', edit_illustration_path(illustration), class: 'btn btn-secondary'
                = link_to 'Delete', illustration, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/illustrations/new.html.haml
%h1 New Illustration
= render 'form'

app/views/illustrations/show.html.haml
%h1= @illustration.title
= image_tag @illustration.image.url(:large)
= simple_format @illustration.blurb

- if user_signed_in?
  = link_to 'Edit', edit_illustration_path(@illustration), class: 'btn btn-secondary'

app/views/items/_form.html.haml
= simple_form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-6
      = f.input :key
      %p It is extremely important that the key is unique
      = f.input :word
      = f.input :reading, as: :text
      = f.input :english, as: :text
      = f.input :notes, as: :text
      = f.input :synonyms
      = f.input :opposites
    .col-sm-6
      = f.input :found_in
      = f.input :japanese, as: :text
      = f.input :origin, as: :text
      = f.input :test
      = f.input :level
      = f.input :category
      = f.button :submit

app/views/items/_results.html.haml
- if user_signed_in?
  = link_to 'New Item', new_item_path, class: 'btn btn-success'
= paginate items, theme: 'twitter-bootstrap-4'
- items.each_slice(3) do |row|
  .row
    - row.each do |item|
      .col-sm-4
        = link_to item do
          .card
            %h5.card-header
              - if item.category == 'Vocab'
                %span.mdi.mdi-dictionary
                Vocabulary
              - if item.category == 'kotowaza'
                %span.mdi.mdi-duck
                Proverb
              - if item.category == 'yjjg'
                %span.mdi.mdi-cat
                Idiom
              - if item.category == 'ateji'
                %span.mdi.mdi-shuffle
                Ateji
            .card-block
              %h1= item.word
              %p
                = item.reading
              %p
                = item.english
              - if user_signed_in?
                %td= link_to 'Edit', edit_item_path(item)
                %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }
= paginate items, theme: 'twitter-bootstrap-4'

app/views/items/ateji.html.haml
%h1
  %span.mdi.mdi-shuffle
  Ateji
%p
  All my study materials for KanKen1, KotoKen, etc. It's all just sorta dumped in here at the moment. Working on organization!
  %br
  漢検やこと検などの勉強資料の保管場所です。必死に整理整頓をやっていますので、ご了承ください。
= render partial: 'results', locals: { items: @items }

app/views/items/edit.html.haml
%h1 Editing DB entry
= render 'form'
= link_to 'Show', @item

app/views/items/idioms.html.haml
%h1
  %span.mdi.mdi-cat
  Idioms
%p
  All my study materials for KanKen1, KotoKen, etc. It's all just sorta dumped in here at the moment. Working on organization!
  %br
  漢検やこと検などの勉強資料の保管場所です。必死に整理整頓をやっていますので、ご了承ください。
= render partial: 'results', locals: { items: @items }

app/views/items/index.html.haml
%h1
  %span.mdi.mdi-database
  All Items
%p
  All my study materials for KanKen1, KotoKen, etc. It's all just sorta dumped in here at the moment. Working on organization!
  %br
  漢検やこと検などの勉強資料の保管場所です。必死に整理整頓をやっていますので、ご了承ください。
= render partial: 'results', locals: { items: @items }

app/views/items/new.html.haml
%h1 Add new entry to DB
= render 'form'

app/views/items/proverbs.html.haml
%h1
  %span.mdi.mdi-duck
  Proverbs
%p
  All my study materials for KanKen1, KotoKen, etc. It's all just sorta dumped in here at the moment. Working on organization!
  %br
  漢検やこと検などの勉強資料の保管場所です。必死に整理整頓をやっていますので、ご了承ください。
= render partial: 'results', locals: { items: @items }

app/views/items/show.html.haml
.card
  .card-block
    %h5.card-title
      %span.mdi.mdi-translate
      Details
    %ul.list-group.list-group-flush
      %li.list-group-item
        %h1= @item.word
      %li.list-group-item
        %p Reading:
        = @item.reading
      %li.list-group-item
        %p English:
        = @item.english
      %li.list-group-item
        %p Notes:
        = @item.notes
      %li.list-group-item
        %p Category:
        = @item.category
- if user_signed_in?
  = link_to 'Edit', edit_item_path(@item)

app/views/items/vocabulary.html.haml
%h1
  %span.mdi.mdi-dictionary
  Vocabulary
%p
  All my study materials for KanKen1, KotoKen, etc. It's all just sorta dumped in here at the moment. Working on organization!
  %br
  漢検やこと検などの勉強資料の保管場所です。必死に整理整頓をやっていますので、ご了承ください。
= render partial: 'results', locals: { items: @items }

app/views/layouts/application.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    %meta{:'http-equiv' => 'x-ua-compatible', content: 'ie=edge'}
    = csrf_meta_tags

    %title Busensei
    %meta{content: 'Busensei'}

    %link{href: "/apple-icon-57x57.png", rel: "apple-touch-icon", sizes: "57x57"}
    %link{href: "/apple-icon-60x60.png", rel: "apple-touch-icon", sizes: "60x60"}
    %link{href: "/apple-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72"}
    %link{href: "/apple-icon-76x76.png", rel: "apple-touch-icon", sizes: "76x76"}
    %link{href: "/apple-icon-114x114.png", rel: "apple-touch-icon", sizes: "114x114"}
    %link{href: "/apple-icon-120x120.png", rel: "apple-touch-icon", sizes: "120x120"}
    %link{href: "/apple-icon-144x144.png", rel: "apple-touch-icon", sizes: "144x144"}
    %link{href: "/apple-icon-152x152.png", rel: "apple-touch-icon", sizes: "152x152"}
    %link{href: "/apple-icon-180x180.png", rel: "apple-touch-icon", sizes: "180x180"}
    %link{href: "/android-icon-192x192.png", rel: "icon", sizes: "192x192", :type => "image/png"}
    %link{href: "/favicon-32x32.png", rel: "icon", sizes: "32x32", :type => "image/png"}
    %link{href: "/favicon-96x96.png", rel: "icon", sizes: "96x96", :type => "image/png"}
    %link{href: "/favicon-16x16.png", rel: "icon", sizes: "16x16", :type => "image/png"}
    %link{href: "/manifest.json", rel: "manifest"}
    %meta{content: "#ffffff", name: "msapplication-TileColor"}
    %meta{content: "/ms-icon-144x144.png", name: "msapplication-TileImage"}
    %meta{content: "#ffffff", name: "theme-color"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body{id: params[:controller], class: params[:action]}
    .wrapper
      = render partial: 'shared/navbar'
      = render partial: 'shared/flash'
      .container-fluid
        = yield
        %br
        %br
      .push
    .footer
      = render partial: 'shared/footer'

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-87452570-1', 'auto');
      ga('send', 'pageview');

app/views/shared/_flash.haml
- if flash
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      .alert.alert-default.animated.fadeInDown.delay.col-sm-6.offset-sm-3#flash{class: "alert-#{name == 'notice' ? 'info' : 'success'}"}
        %a.close{'data-dismiss' => 'alert'}
          &times;
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_footer.haml
%footer
  .container-fluid.m-t-3.m-b-1
    .row
      .col-sm-6
        %small
          Copyright
          - if user_signed_in?
            = link_to '©', destroy_user_session_path, method: :delete
          - else
            = link_to '©', new_user_session_path
          2016 Bret Mayer
      .col-sm-6
        .float-sm-right
          %a{href: "http://www.superpencil.com/?utm_source=timegiver&utm_medium=footer+link&utm_campaign=project", class: 'superpencil', alt: 'Superpencil'}
            %small Design and Development by
            %b.tag.tag-secondary
              = image_tag 'superpencil.svg', alt: 'Superpencil'
              Superpencil

app/views/shared/_navbar.haml
%nav.navbar.navbar-fixed-top.navbar-light.bg-faded
  = link_to root_url, class: 'navbar-brand' do
    = t('.brand')
  %ul.nav.nav-pills.float-md-left
    %li.nav-item.dropdown
      %button#itemMenu.btn.btn-primary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
        %span.mdi.mdi-book-open-page-variant
        Study Material
      .dropdown-menu{"aria-labelledby" => "itemMenu"}
        = link_to items_path, class: 'dropdown-item' do
          %span.mdi.mdi-database
          All Items
        = link_to vocabulary_path, class: 'dropdown-item' do
          %span.mdi.mdi-dictionary
          Vocabulary
        = link_to proverbs_path, class: 'dropdown-item' do
          %span.mdi.mdi-duck
          Proverbs
        = link_to idioms_path, class: 'dropdown-item' do
          %span.mdi.mdi-cat
          Idioms
        = link_to ateji_path, class: 'dropdown-item' do
          %span.mdi.mdi-shuffle
          Ateji
  %ul.nav.nav-pills.float-md-right
    %li.nav-item
      = link_to illustrations_path, class: 'nav-link' do
        %span.mdi.mdi-cards
        = t('.illustrations')
    %li.nav-item
      = link_to videos_path, class: 'nav-link' do
        %span.mdi.mdi-video
        = t('.videos')
    %li.nav-item
      = link_to contact_path, class: 'nav-link' do
        %span.mdi.mdi-account
        = t('.about_contact')
    %li.nav-item
      - if I18n.locale == :en
        = link_to '日本語', current_path_new_locale('ja'.to_sym), class: 'btn btn-secondary'
      - else
        = link_to 'English', current_path_new_locale('en'.to_sym), class: 'btn btn-secondary'

app/views/videos/_form.html.haml
= simple_form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title
  %p Title can be anything
  = f.input :tag
  %p The tag is the identifier of the YouTube video
  = f.button :submit

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1
  %span.mdi.mdi-video
  Videos
%br
- if user_signed_in?
  = link_to 'New Video', new_video_path, class: 'btn btn-success'
  %br
  %br
- @videos.each_slice(2) do |row|
  .row
    - row.each do |video|
      .col-sm-6
        = link_to video do
          .card
            %h5.card-header
              = video.title
            .card-block
              .embed-responsive.embed-responsive-16by9
                %iframe{allowfullscreen: "", src: "https://www.youtube.com/embed/#{video.tag}", class: 'embed-responsive-item'}
              - if user_signed_in?
                %br
                = link_to 'Edit', edit_video_path(video), class: 'btn btn-secondary'
                = link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-secondary'

app/views/videos/new.html.haml
%h1 Add new Video
= render 'form'

app/views/videos/show.html.haml
%h1= @video.title
.embed-responsive.embed-responsive-16by9
  %iframe{allowfullscreen: "", src: "https://www.youtube.com/embed/#{@video.tag}", class: 'embed-responsive-item'}
- if user_signed_in?
  = link_to 'Edit', edit_video_path(@video)

app/views/welcomes/index.haml
.row
  .col-xs-4.col-sm-3.col-lg-2
    = image_tag 'bret_tv.jpg', class: 'img-rounded'
  .col-xs-8.col-sm-9.col-lg-10
    %h5= t('.intro')
    %a{href: 'https://twitter.com/busensei', target:'_blank', class: 'btn btn-info'}
      %span.mdi.mdi-twitter
      Twitter
    %br
    %br
    .alert.alert-warning
      %b= t('.alert.title')
      = t('.alert.body')
%br
%br
.row
  .col-lg-4
    .card
      .card-block
        %h5.card-title
          %span.mdi.mdi-translate
          = t('.random_vocab')
        %ul.list-group.list-group-flush
          - @items.each do |item|
            %li.list-group-item
              = link_to item do
                %h1= item.word
                %p= item.reading
                %p= item.english
  .col-lg-4
    .card
      .card-block
        %h5.card-title
          %span.mdi.mdi-video
          = t('.latest_video')
        - @videos.each do |video|
          .embed-responsive.embed-responsive-16by9
            %iframe{allowfullscreen: "", src: "https://www.youtube.com/embed/#{video.tag}", class: 'embed-responsive-item'}
  .col-lg-4
    .card
      .card-block
        %h5.card-title
          %span.mdi.mdi-cards
          = t('.latest_illustration')
        - @illustrations.each do |illustration|
          = link_to illustration do
            = illustration.title
            = image_tag illustration.image.url(:medium), class: 'img-fluid img-rounded'
            = simple_format illustration.blurb